#!/bin/bash
sudo systemctl stop kestrel-pokercards-wa.service
sudo systemctl stop kestrel-pokercards.service
sudo dotnet publish
sudo systemctl start kestrel-pokercards.service
echo 'Successfully published'