name: prod-ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Version Number
        run: echo "VERSION_NUMBER=$(ls *.md | sort -r | head -1 | sed 's/.md//g')" >> $GITHUB_ENV
        working-directory: ./release-notes/versions
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/Server/Dockerfile
          push: true
          tags: reedptaylor/scrumstorysizer:latest,reedptaylor/scrumstorysizer:${{ env.VERSION_NUMBER }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.SERVER_SSH_KNOWN_HOSTS }}
      - name: Docker Run
        run: ssh reed@${{ secrets.SERVER_SSH_HOST }} 'docker container rm -f scrumstorysizer-prod | docker run --rm -d --name scrumstorysizer-prod --pull always -p 5008:5000/tcp reedptaylor/scrumstorysizer:latest'
