name: test

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0"

    - name: dotnet restore
      run: dotnet restore
    - name: dotnet build
      run: dotnet build --no-restore
    - name: dotnet test
      run: dotnet test --no-build --verbosity normal